# Core server configuration
# Consider this your defaults

# Allows you to expose ports
server:
  port: "8080"
  host: "0.0.0.0"

# Database configuration
database:
  path: "smsrequest.DB"

# Configurations for how to use Filter API
filter:
  enabled: true # Turns on or off usage of the filter API
  apiurl: "http://192.168.8.100:8000/api/filter/sms" # point me to your filter API
  # set the size of how many concurrent requests to the filter api will be made
  # by using a buffered chan to limit. Use this to reduce potential impact on
  # filterapi (which can be run locally and is CPU ony so it's a hungry boi)
  # Valid Values = [0:Unlimited, INT] 
  maxconcurrent: 5 # max concurrent filter requests (just simple throttling)
  # set size of the result channel (think of it as how many results from filter api
  # can be processed at once). I would NOT specify this typically cause it's a bit
  # silly since go manages it, but if you want to you can true limiting it reduce 
  # resourceusage.
  # Valid Values: [0:Unlimited, INT]
  resultchansize: 10
